#-------------------------------------------embedded server config
server:
  port: 8080
#-------------------------------------------spring config
spring:
  application:
    name: seckill
  datasource:
    data-username: root
    data-password: tjhdmysqlmms800
    url: jdbc:mysql://localhost:3306/seckill?characterEncoding=utf8&useSSL=true&useUnicode=true
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      web-stat-filter:
        exclusions: .js,.gif,.jpg,.png,.css,.ico,/druid/
      stat-view-servlet:
        loginUsername: druid
        login-password: druid
  redis:
    host: localhost
    port: 6379
    password: 123456
#-------------------------------------------mybatis config
mybatis:
  type-aliases-package: com.ternence.seckill.domain.model
  mapper-locations: classpath:mappers/*

